LitReview/LitReview/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView)

from django.conf import settings
from django.conf.urls.static import static

import core.views
import following.views
import ticketing.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(
            template_name="core/login.html",
            redirect_authenticated_user=True),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='core/password_change_form.html'),
         name='password_change'
         ),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='core/password_change_done.html'),
         name='password_change_done'
         ),
    path('signup/', core.views.signup_page, name='signup'),
    path('home/', core.views.home, name='home'),

    path('subscription/', following.views.subcription_page, name='subcription'),
    path('search_users/', following.views.search_users, name='search-users'),
    path('subscription/subscribe/', following.views.subscribe_user, name='subscribe-user'),
    path('subcription/<int:follow_id>/delete/', following.views.unsubscribe_user, name='unsubscribe-user'),

    path('ticket/create/', ticketing.views.create_ticket, name='create-ticket'),
    path('<int:ticket_id>/review/create/', ticketing.views.create_review, name='create-review'),
    path('ticket-and-review/create', ticketing.views.create_ticket_and_review, name="create-ticket-and-review"),

    path('posts/', ticketing.views.posts, name='posts'),
    path("posts/<str:post_type>/<int:post_id>/update/", ticketing.views.post_update, name='post-update'),
    path("posts/<str:post_type>/<int:post_id>/delete/", ticketing.views.post_delete, name='post-delete')
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LitReview/ticketing/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.fields.CharField(max_length=128)
    description = models.fields.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.fields.DateTimeField(auto_now_add=True)

    @property
    def has_review(self):
        try:
            Review.objects.get(ticket__pk=self.id)
        except Review.DoesNotExist:
            return False
        return True

    @property
    def type(self):
        return "ticket"


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.fields.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    header = models.fields.CharField(max_length=128)
    body = models.fields.TextField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

    @property
    def type(self):
        return "review"

    @property
    def stars(self):
        result = ""
        for i in range(5):
            result += "★" if i < self.rating else "☆"
        return result

LitReview/ticketing/forms.py
from django import forms

from . import models


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ['title', 'description', 'image']


class ReviewForm(forms.ModelForm):
    CHOICES = [('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]
    rating = forms.ChoiceField(label="Note", choices=CHOICES, widget=forms.RadioSelect)
    header = forms.CharField(label="Titre", widget=forms.TextInput)
    body = forms.CharField(label="commentaire", widget=forms.Textarea)

    class Meta:
        model = models.Review
        fields = ['header', 'rating', 'body']

LitReview/ticketing/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from . import forms
from . import models
from django.contrib import messages


@login_required
def create_ticket(request):
    ticket_form = forms.TicketForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('home')
    return render(request, 'ticketing/create_ticket.html', context={'ticket_form': ticket_form})


@login_required
def create_review(request, ticket_id):
    review_form = forms.ReviewForm()
    ticket = models.Ticket.objects.get(id=ticket_id)
    if request.method == 'POST':
        review_form = forms.ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect('home')

    return render(request, 'ticketing/create_review.html', context={'review_form': review_form, 'ticket': ticket})


@login_required
def create_ticket_and_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if ticket_form.is_valid() and review_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            review = review_form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            return redirect('home')
    context = {
        'review_form': review_form,
        'ticket_form': ticket_form
    }

    return render(request, 'ticketing/create_ticket_and_review.html', context)


@login_required
def posts(request):
    tickets = models.Ticket.objects.filter(user=request.user)
    reviews = models.Review.objects.filter(user=request.user)
    posts = list(tickets) + list(reviews)
    posts.sort(key=lambda x: x.time_created, reverse=True)
    context = {'posts': posts}

    return render(request, 'ticketing/posts.html', context)


@login_required
def post_update(request, post_type, post_id):
    if post_type == "ticket":
        post = models.Ticket.objects.get(id=post_id)
    else:
        post = models.Review.objects.get(id=post_id)

    if request.method == "POST":
        print(request.FILES)
        if post_type == "ticket":
            form = forms.TicketForm(request.POST, request.FILES, instance=post)
        else:
            form = forms.ReviewForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts')
    else:
        if post_type == "ticket":
            form = forms.TicketForm(instance=post)
        else:
            form = forms.ReviewForm(instance=post)

    context = {
        "form": form,
        "post": post
    }
    return render(request, 'ticketing/post_update.html', context)


@login_required
def post_delete(request, post_type, post_id):
    if post_type == "ticket":
        post = models.Ticket.objects.get(id=post_id)
    else:
        post = models.Review.objects.get(id=post_id)
    context = {"post": post}

    if request.method == "POST":
        post.delete()
        messages.add_message(request,
                             messages.INFO,
                             "le post a été supprimé avec succès!")
        return redirect('posts')

    return render(request, 'ticketing/post_delete.html', context)

LitReview/ticketing/templates/ticketing/create_review.html
{% extends 'base.html' %}

{% block content %}
    <h2>Creer une critique</h2>
    <div class="post">
        {% include "ticket.html" with post=ticket %}
      </div>
    <form class="formulaire" method="post" >
        {{ review_form.as_p }}
        {% csrf_token %}
        <button type="submit" >Publier</button>
    </form>
{% endblock content %}

LitReview/ticketing/templates/ticketing/create_ticket.html
{% extends 'base.html' %}
{% block content %}
    <h1>Creer un ticket</h2>
    <form class="formulaire" method="post" enctype="multipart/form-data">
        {{ ticket_form.as_p }}
        {% csrf_token %}
        <button class="Envoyer" type="submit" >Envoyer</button>
    </form>
{% endblock content %}

LitReview/ticketing/templates/ticketing/create_ticket_and_review.html
{% extends 'base.html' %}

{% block content %}
    <h2>Creer un ticket</h2>
        <form class="formulaire" method="post" enctype="multipart/form-data">
            {{ ticket_form.as_p }}
            {{ review_form.as_p }}
            {% csrf_token %}
            <button type="submit" >Publier</button>
        </form>
{% endblock content %}

LitReview/ticketing/templates/ticketing/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1> Supprimer le post</h1>
    {% if post.type == "ticket"%}
        <p>Etes-vous sûr de vouloir supprimer le post : {{ post.title}} ?</p>
    {% else %}
        <p>Etes-vous sûr de vouloir supprimer le post : {{ post.header}} ?</p>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer"> 
    </form>

{% endblock %}

LitReview/ticketing/templates/ticketing/post_update.html
{% extends 'base.html' %}

{% block content %}
  <form class="formulaire" method="post" enctype="multipart/form-data">
    <p>critique</p>
    {% csrf_token %}
    {% if post.type == "ticket" %}
      <h1> Modifier votre ticket</h1>
      <p><label>titre</label>
        {{ form.title }}</p>

      <p><label>description</label>
        {{ form.description }}</p>
      <p>
      {% if post.image.url is not None %}
        <img src="{{ post.image.url }}" alt="" height=25% width=25%>
        <label for="image-clear_id">effacer</label>
        <input type="checkbox" name="image-clear" id="image-clear_id">
      
      {% else %}
        <p>Le ticket ne comporte pas d'image</p>
      {% endif %}</p>
        <label for="id_image">modification</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    {% else %}
      <h1> Modifier votre critique</h1>
      <div class="post">
        {% include "ticket.html" with post=post.ticket %}
      </div>
        {{ form.as_p }}

    {% endif %}

    <input type="submit" value="Envoyer">

 </form>
{% endblock %}

LitReview/ticketing/templates/ticketing/posts.html
{% extends 'base.html' %}

{% block content %}
    <h1>post</h1>
    {% for post in posts %}
        <div class = "post">
            {% if post.type == "ticket" %}
                <p> Vous avez publié un ticket </p>
                {% include "ticket.html" %}
                
            {% elif post.type == "review" %} 
                {% include "review.html" %}
            {% endif %}
            <div class="envoyer">
                <form method="GET" action="{% url 'post-update' post.type post.id %}">
                    {% csrf_token %}
                    <button type='submit'>Modifier</button>
                </form>

                <form method="GET" action="{% url 'post-delete' post.type post.id %}">
                    {% csrf_token %}
                    <button type='submit'>Supprimer</button>
                </form>
            </div>
        </div>
    {% endfor %}
{% endblock content %}